package com.example.lesson3fragments

const val FRAGMENT_A_TAG = "FRAGMENT_A_TAG"
const val FRAGMENT_B_TAG = "FRAGMENT_B_TAG"
const val FRAGMENT_C_TAG = "FRAGMENT_C_TAG"
const val FRAGMENT_D_TAG = "FRAGMENT_D_TAG"
const val FRAGMENT_USER_LIST_TAG = "FRAGMENT_USER_LIST_TAG"
const val FRAGMENT_USER_EDIT_TAG = "FRAGMENT_USER_EDIT_TAG"
const val STRING_TO_C_KEY = "STRING_TO_C_KEY"
const val REQUEST_KEY_EDIT = "EditFragment_REQUEST_KEY"